allowBuilds:
  '@playwright/browser-chromium': false
  '@swc/core': true
  better-sqlite3: true
  core-js: set this to true or false
  esbuild: true
  onnxruntime-node: false
  protobufjs: false
  sharp: true
